<!-- Bootstrap core CSS -->
<link href="resources/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

<!-- Favicons -->
<link rel="apple-touch-icon" href="resources/images/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="resources/images/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="resources/images/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="resources/images/favicons/manifest.json">
<link rel="mask-icon" href="resources/images/favicons/safari-pinned-tab.svg" color="#7952b3">
<link rel="icon" href="resources/images/favicons/favicon.ico">
<meta name="theme-color" content="#7952b3">

<!-- Custom styles for this template -->
<link href="resources/css/style.css" rel="stylesheet">
<link href="resources/css/media.css" rel="stylesheet">